# añadimos el repo de docker
- name: add repo docker
  become: true  
  command: "{{item}}" 
  with_items:
   - dnf config-manager --add-repo=https://download.docker.com/linux/centos/docker-ce.repo
#   - dnf install docker-ce-20.10.6-3.el8 -y

# instalamos docker
- name: Install common packages
  become: true
  ansible.builtin.dnf:
   name: "{{item}}"
   state: latest    
  with_items:
   - docker-ce-20.10.6-3.el8
  
# activamos servicio de docker
- name: Enable Docker service
  become: true
  ansible.builtin.systemd:
    name: docker
    enabled: yes

#arrancamos servicio docker 
- name: Ensure Docker service is running
  become: true
  ansible.builtin.systemd:
    name: docker
    state: started

#configuramos el repo de kubernetes       
- name: configurar repo de kubernetes
  become: true
  ansible.builtin.lineinfile:
    path: /etc/yum.repos.d/kubernetes.repo
    backup: yes
    line: "{{item}}"
    create: yes
    state: present
  with_items:
     - "[kubernetes]"
     - "name=Kubernetes"
     - "baseurl=https://packages.cloud.google.com/yum/repos/kubernetes-el7-x86_64"
     - "enabled=1"
     - "gpgcheck=1"
     - "repo_gpgcheck=1"
     - "gpgkey=https://packages.cloud.google.com/yum/doc/yum-key.gpg https://packages.cloud.google.com/yum/doc/rpm-package-key.gpg"
     - "exclude=kubelet kubeadm kubectl"
  
#instalamos kubelet
- name: install and active kubernetes
  become: true  
  command: "{{item}}" 
  with_items:
   - "dnf install -y kubelet kubeadm kubectl --disableexcludes=kubernetes"
   
# activamos servicio de kubelet
- name: Enable kubelet service
  become: true
  ansible.builtin.systemd:
    name: kubelet
    enabled: yes

#arrancamos servicio kubelet 
- name: Ensure kubelet service is running
  become: true
  ansible.builtin.systemd:
    name: kubelet
    state: started   

