- name: open ports
  become: true  
  shell: "{{item}}" 
  with_items:
   - firewall-cmd --zone=public --permanent --add-port={10250,30000-32767}/tcp
   - firewall-cmd --reload

# mostramos que la variable guardada en el master la veo desde el worker
- name: debug token
  become: true
  debug: msg="{{hostvars['mastercp2.westeurope.cloudapp.azure.com']['token_join'].stdout}}"
     
# ejecutamos el valor que hemos registrado del join command de master en los workers 
- name: execute join
  become: true  
  command: "{{hostvars['mastercp2.westeurope.cloudapp.azure.com']['token_join'].stdout}}"     
  ignore_errors: yes
