## Rol para la configuración de kubernetes, en este caso para los workers ##

# abrimos puertos firewall
- name: open ports
  become: true  
  ansible.posix.firewalld: 
    zone: public
    permanent: yes
    port: "{{item}}"
    state: enabled
  loop:
   - 10250/tcp
   - 10255/tcp
   - 8285/udp
   - 8472/udp
   - 30000-32767/tcp

# añade masquerade firewall
- name: firewall
  become: true
  ansible.posix.firewalld:
    masquerade: yes
    state: enabled
    permanent: yes

# volvemos a cargar el firewall 
- name: reload firewall
  become: true  
  shell: "firewall-cmd --reload" 

- name: Get name_dns_master
  become: true
  debug: {{dns_namemaster}}
  register: mastername

# mostramos que la variable guardada en el master la veo desde el worker
- name: debug token
  become: true
  debug: msg = "{{hostvars['mastername']['token_join'].stdout}}"
  
     
# ejecutamos el valor que hemos registrado del join command de master en los workers 
# activamos ignore_errors, si el join ya se hubiera hecho que continúe la ejecución
#- name: execute join
#  become: true  
#  command: "{{hostvars['{{dns_namemaster}}']['token_join'].stdout}}"     
#  ignore_errors: yes
