- name: install ingress controller
  become: true  
  shell: kubectl apply -f https://raw.githubusercontent.com/haproxytech/kubernetes-ingress/v1.5/deploy/haproxy-ingress.yaml

- name: patch externalIp and LoadBalancer
  become: true
  shell: |
     kubectl patch service haproxy-ingress -p '{"spec":{"externalIPs":["{{ private_lan_master }}"]},"loadBalancerIP": "{{ private_lan_master }}", "type": "loadBalancer"}' -n haproxy-controller  
