- name: install ingress controller
  become: true  
  shell: kubectl apply -f https://raw.githubusercontent.com/haproxytech/kubernetes-ingress/v1.5/deploy/haproxy-ingress.yaml

#- name: install externalIp and LoadBalancer
#  become: true
#  command: "kubectl patch service haproxy-ingress -p '{"spec":{"externalIPs":["10.0.1.50"]},"loadBalancerIP": "10.0.1.50", "type": "loadBalancer"}' -n haproxy-controller"
 # shell: 'kubectl patch service controller-ingress-nginx-controller -p '{"spec":{"externalIPs":["10.0.1.50"]},"loadBalancerIP": "10.0.1.50", "type": "loadBalancer"}''

- name: patch externalIp and loadBalancer
  template:
    src: proxy.sh.j2
    dest: ./
    owner: root
    group: root
    mode: 0644
  become: yes
  
- name: execute patch
  become: true
  shell: sh proxy.sh
