## Rol para la creación y permisos del usuario en kubernetes ##

# creamos usuario para acceder al cluster
- name: create user for access to the cluster
  become: true  
  ansible.builtin.user:
      name: kubeadmin
      create_home: yes
      password: kubeadmin
  ignore_errors: yes 
  
# creación del directorio .kube
- name: Create .kube directory
  become: true
  file:
    path: /home/kubeadmin/.kube
    state: directory
    owner: "kubeadmin"
    group: "kubeadmin"
  ignore_errors: yes    
     
# copiamos config al usuario kubeadmin
- name: Copy k8s config
  become: true
  copy:
    src: /etc/kubernetes/admin.conf
    dest: /home/kubeadmin/.kube/config
    owner: "kubeadmin"
    group: "kubeadmin"
    remote_src: yes
       
# permisos
- name: Chown kubeadmin 
  become: true  
  shell: | 
     chown kubeadmin. /home/kubeadmin/.kube/config
    
# creamos entrada en el fichero kubeadmin
- name: Create entry sudores file
  become: true
  copy:
    content: 'kubeadmin ALL=(ALL:ALL) NOPASSWD:ALL'
    dest: /etc/sudoers.d/kubeadmin
    mode: 0440   
