- hosts: all
  gather_facts: false
  tasks:
  - name: Install common packages
    become: true
    ansible.builtin.dnf:
     name: "{{item}}"
     state: latest    
    with_items:
     - python3
     - chrony
     - nfs-utils
     - nfs4-acl-tools
     - wget
     
  - name: Update dnf repository
    become: true
    ansible.builtin.dnf:
      update_only: yes 
      update_cache: yes
     
  - name: Enable and started Chrony service
    become: true
    ansible.builtin.systemd:
      name: chronyd
      enabled: yes
      state: started
      daemon_reload: true
         
  - name: Set timezone to Europe/Madrid
    become: true
    community.general.timezone:
      name: Europe/Madrid
      
  #- name: Unconditionally reboot the machine with all defaults
  #  reboot:
     
  - name: timedatectl set-ntp
    become: true
    command: timedatectl set-ntp true
  
  - name: SELinux estuviera activado lo desativamos
    become: true
    command: sed -i s/=enforcing/=disabled/g /etc/selinux/config
     
  - name: firewall, modprobe
    become: true
    command: "{{item}}" 
    with_items:
    # firewall y cortafuegos
    - systemctl enable firewalld
    - systemctl start firewalld
    - modprobe br_netfilter
    - firewall-cmd --add-masquerade --permanent
    - firewall-cmd --reload
    
  - name: tráfico de cortafuegos
    become: true
    ansible.builtin.lineinfile:
      path: /etc/sysctl.d/k8s.conf
      backup: yes
      line: "{{item}}"
      create: yes
      state: present
    with_items:
    - net.bridge.bridge-nf-call-ip6tables = 1
    - net.bridge.bridge-nf-call-iptables = 1
    async: 10
    poll: 2
  
  - name: aplicar cambios
    become: true
    command: sysctl --system
  
  - name: desactivar swap
    become: true
    command: swapoff -a
    
  - name: borrar linea swap en fstab
    become: true
    ansible.builtin.lineinfile:
      path: /etc/fstab
      # String to Search
      regexp: "swap" 
      # State is set to Absent to remove if the Searching Line is found
      state: absent
      backup: yes
  
   
  
  
  
