- hosts: all
  gather_facts: false
  tasks:
  - name: install common components
    become: true
    command: "{{item}}" 
    with_items:
    - dnf install chrony –y
    - systemctl enable chronyd
    - dnf update –y
    - reboot
    - dnf install python3 -y
  # - se instala git y ansible en la máquina que se va a usar de controlador de ansible, en este caso ya viene instalada en el CLI de azure 
  # - dnf install git ansible -y
  
  
  
