- hosts: all
  gather_facts: false
  tasks:
  # uso become para acceder como superusuario 
  - name: actualizamos máquinas al último nivel
    become: true
    command: dnf update -y

  - name: sincronización horaria
    become: true
    command: timedatectl set-timezone Europe/Madrid
  
  - name: enable chronyd
    become: true
    command: systemctl enable chronyd
    
  - name: arrancar chronyd
    become: true
    command: systemctl start chronyd

  - name: timedatectl set-ntp
    become: true
    command: timedatectl set-ntp true
  
  - name: SELinux estuviera activado lo desativamos
    become: true
    command: sed -i s/=enforcing/=disabled/g /etc/selinux/config
  
  - name: instalación de paquetes necesarios
    become: true
    command: dnf install nfs-utils nfs4-acl-tools wget -y
  
  - name: firewall, modprobe
    become: true
    command: "{{item}}" 
    with_items:
    # firewall y cortafuegos
    - systemctl enable firewalld
    - systemctl start firewalld
    - modprobe br_netfilter
    - firewall-cmd --add-masquerade --permanent
    - firewall-cmd --reload
    
  - name: tráfico de cortafuegos
    become: true
    ansible.builtin.lineinfile:
      path: /etc/sysctl.d/k8s.conf
      backup: yes
      line: "{{item}}"
      create: yes
      state: present
    with_items:
    - net.bridge.bridge-nf-call-ip6tables = 1
    - net.bridge.bridge-nf-call-iptables = 1
    async: 10
    poll: 2
    
  - name: desactivar swap
    become: true
    command: swapoff -a
    
    
  
    
    
    
