# Playbook para la instalación de kubernetes en master y workers
- hosts: all
  vars_files:
    - "group_vars/vars-cp2.yaml"
  gather_facts: false
  roles:
   - kubernetes
   
  

 
 
 
 
 

      
  
  
  
    
    
    
