
# Hago que compartan playbook estos dos roles, porque en una de las tareas del rol se comparte una variable #

- hosts: master
  gather_facts: false
  roles:
   - configurekubernetes
          
- hosts: workers
  gather_facts: false
  roles:
   - configurekubernetesnodes



