- hosts: workers
  gather_facts: true
  tasks:
   - name: open ports
     become: true  
     shell: "{{item}}" 
     with_items:
      - firewall-cmd --zone=public --permanent --add-port={10250,30000-32767}/tcp
      - firewall-cmd --reload
      
   - name: Join Cluster
     become: true
     shell: "{{ hostvars['kubemaster']['kubernetes_join_command'] }}"
     
   
     
     
     
     
     


