- hosts: workers
  gather_facts: true
  tasks:
   - name: open ports
     become: true  
     shell: "{{item}}" 
     with_items:
      - firewall-cmd --zone=public --permanent --add-port={10250,30000-32767}/tcp
      - firewall-cmd --reload
      
   - name: Copy the join command to server location
     copy: src=token_join.sh dest=/tmp/token_join.sh

   - name: Copy the join command to server location
     command: chmod +x /tmp/token_join.sh

   - name: Join the node to cluster 
     command: sh /tmp/token_join.sh
     
   
     
     
     
     
     


