- hosts: workers
  gather_facts: false
  tasks:
   - name: open ports
     become: true  
     shell: "{{item}}" 
     with_items:
      - firewall-cmd --zone=public --permanent --add-port={10250,30000-32767}/tcp
      - firewall-cmd --reload
     
      
   
     
     
     


