- hosts: master
  gather_facts: false
  tasks:
   # Creamos un namespace
   #- name: Create namespace 
   #  become: true
   #  community.kubernetes.k8s: 
   #     namespace: webapp-volumes
  - name: Create namespace 
    become: true
    shell: kubectl create namespace webapp-volumes
  
  # copiamos config al usuario ansible
   - name: Copy nfs-pv.yaml to master
     become: true
     copy:
       src: nfs-pv.yaml 
       dest: ./
         
  - name: Copy nfs-pv.yaml to master
     become: true
     shell: kubectl apply -f nfs-pv.yaml
       
       
