- hosts: master
  gather_facts: false
  tasks:
   - name: Copy k8s config
     become: true
     copy:
       src: ./etc/kubernetes/admin.conf
       dest: /home/{{ ansible_user }}/.kube/config
       owner: "{{ ansible_user }}"
       group: "{{ ansible_user }}"
       remote_src: yes



apiVersion: apps/v1
kind: Deployment
metadata:
  name: webapp
  labels:
    app: webapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: webapp
  template:
    metadata:
      labels:
        app: webapp
    spec:
      containers:
      - name: webapp
        image: quay.io/rhte_2019/webapp:v1      
        ports:
        - containerPort: 80
