- hosts: master
  gather_facts: false
  tasks:
   # Creamos un namespace
   #- name: Create namespace 
   #  become: true
   #  community.kubernetes.k8s: 
   #     namespace: webapp-volumes
  - name: Create namespace 
    become: true
    shell: kubectl create namespace webapp-volumes
  
  - name:  
