- hosts: master
  gather_facts: false
  tasks:
  - name: create nfs
    become: true
    command: "{{item}}" 
    with_items:
    - lsblk
    - pvcreate /dev/vdb
    - vgcreate data_vg /dev/vdb
    - vgdisplay data_vg
    - lvcreate -l+2559 -n nfs_lv /dev/data_vg
    - lvs
    - mkfs.xfs /dev/data_vg/nfs_lv
    - mkdir /srv/nfs
    - echo "/dev/data_vg/nfs_lv        /srv/nfs                xfs     defaults        0 0" >> /etc/fstab
    - mount -a
    - df -hP
    - dnf install nfs-utils net-tools -y
    - systemctl  enable nfs-server
    - systemctl start nfs-server
    - cat /etc/exports 
    - exportfs -r
    - exportfs -s
    
  - name: open ports
    become: true
    command: "{{item}}" 
    with_items:    
    - firewall-cmd --permanent --add-service=nfs
    - firewall-cmd --permanent --add-service=rpc-bind
    - firewall-cmd --permanent --add-service=mountd
    - firewall-cmd --reload
    
