- hosts: all
  gather_facts: false
  tasks:
  # uso become para acceder como superusuario 
  - name: actualizamos máquinas al último nivel
    become: true
    command: dnf update -y

  - name: sincronización horaria
    become: true
    command: timedatectl set-timezone Europe/Madrid

    

