- hosts: master
  gather_facts: false
  tasks:
  - name: Create a new primary partition
    become: true
    community.general.parted:
      device: /dev/sdc
      number: 1
      state: present
    async: 300
    poll: 5
    register: nfs_partition

# Create logical volume
# https://docs.ansible.com/ansible/latest/collections/community/general/lvol_module.html 
  - name: Create Volume Group on /dev/sdc with physical extent size = 10g
    become: true  
    community.general.lvg:
      vg: nfs-vg
      pvs: /dev/sdc1
      force: no
      state: present
    async: 10
    poll: 2
    when: nfs_partition.changed

  - name: Create a logical volume
    become: true
    community.general.lvol:
      vg: nfs-vg
      lv: nfs-lv
      size: 100%FREE
      force: no
      state: present
    async: 10
    poll: 2
    when: nfs_partition.changed


  - name: Create xfs filesystem on nfs data partition
    become: true
    community.general.filesystem:
      fstype: xfs
      dev: /dev/nfs-vg/nfs-lv
      force: yes
    async: 300
    poll: 5
    when: nfs_partition.changed

