# copiamos apple-yaml al directorio de master
- name: Copy apple.yaml to master
  become: true
  copy:
    src: apple.yaml 
    dest: ./
  
# aplicamos apple
- name: Apply apple.yaml
  become: true
  shell: kubectl apply -f apple.yaml
